openapi: 3.1.0
info:
  title: Crossword Game
  description: Crossword Game
  version: 1.0.0
paths:
  /health:
    get:
      summary: Health check
      operationId: healthCheck
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthcheckResponse'
  /api/v1/game:
    post:
      summary: Create a new game
      operationId: createGame
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateGameRequest'
      responses:
        '201':
          description: Created
          headers:
            Location:
              description: Location of the new game
              schema:
                type: string
                format: uri
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateGameResponse'
  /api/v1/game/{game_id}:
    get:
      summary: Get game state
      operationId: getGameState
      parameters:
        - name: game_id
          in: path
          required: true
          description: ID of the game
          schema:
            $ref: '#/components/schemas/GameId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameState'
        '404':
          description: Not Found
  /api/v1/game/{game_id}/player/{player_id}:
    get:
      summary: Get player state
      operationId: getPlayerState
      parameters:
        - name: game_id
          in: path
          required: true
          description: ID of the game
          schema:
            $ref: '#/components/schemas/GameId'
        - name: player_id
          in: path
          required: true
          description: ID of the player
          schema:
            $ref: '#/components/schemas/PlayerId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayerState'
        '404':
          description: Not Found
  /api/v1/game/{game_id}/player/{player_id}/announce:
    post:
      summary: Announce a letter
      operationId: submitAnnouncement
      parameters:
        - name: game_id
          in: path
          required: true
          description: ID of the game
          schema:
            $ref: '#/components/schemas/GameId'
        - name: player_id
          in: path
          required: true
          description: ID of the player
          schema:
            $ref: '#/components/schemas/PlayerId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnnounceRequest'
      responses:
        '200':
          description: Announced
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnnounceResponse'
        '400':
          description: Bad Request
  /api/v1/game/{game_id}/player/{player_id}/place:
    post:
      summary: Place a letter
      operationId: submitPlacement
      parameters:
        - name: game_id
          in: path
          required: true
          description: ID of the game
          schema:
            $ref: '#/components/schemas/GameId'
        - name: player_id
          in: path
          required: true
          description: ID of the player
          schema:
            $ref: '#/components/schemas/PlayerId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlaceRequest'
      responses:
        '200':
          description: Placed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlaceResponse'
        '400':
          description: Bad Request
  /api/v1/game/{game_id}/player/{player_id}/score:
    get:
      summary: Get player score
      operationId: getPlayerScore
      parameters:
        - name: game_id
          in: path
          required: true
          description: ID of the game
          schema:
              $ref: '#/components/schemas/GameId'
        - name: player_id
          in: path
          required: true
          description: ID of the player
          schema:
              $ref: '#/components/schemas/PlayerId'
      responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/PlayerScore'
          '404':
            description: Not Found

components:
  schemas:
    HealthcheckResponse:
      type: object
      properties:
        start_time:
          type: string
          format: date-time
      required:
        - start_time
    CreateGameRequest:
      type: object
      properties:
        player_count:
          type: integer
          minimum: 1
          maximum: 4
      required:
        - player_count
    CreateGameResponse:
      type: object
      properties:
        game_id:
          $ref: '#/components/schemas/GameId'
      required:
        - game_id
    GameState:
      type: object
      properties:
        game_id:
          $ref: '#/components/schemas/GameId'
        status:
          type: string
          enum:
            - awaiting_announcement
            - awaiting_placement
            - finished
        player_count:
          type: integer
          minimum: 1
        squares_filled:
          type: integer
          minimum: 0
        current_announcing_player_id:
          $ref: '#/components/schemas/PlayerId'
      required:
        - game_id
        - status
        - player_count
        - squares_filled
        - current_announcing_player_id
    PlayerState:
      type: object
      properties:
        board:
          type: array
          items:
            type: array
            items:
              $ref: '#/components/schemas/Letter'
      required:
        - board
    PlayerScore:
      type: object
      properties:
        score:
          type: integer
          minimum: 0
      required:
        - score
    AnnounceRequest:
      type: object
      properties:
        letter:
          $ref: '#/components/schemas/Letter'
      required:
        - letter
    AnnounceResponse:
      type: object
    PlaceRequest:
      type: object
      properties:
        row:
          type: integer
          minimum: 0
        column:
          type: integer
          minimum: 0
        letter:
          $ref: '#/components/schemas/Letter'
      required:
        - row
        - column
        - letter
    PlaceResponse:
      type: object
    GameId:
      description: ID of a game
      type: string
    PlayerId:
      description: ID of a player
      type: integer
      minimum: 0
    Letter:
      description: A single letter
      type: string
      maxLength: 1